### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by Shoham12** [percona/mongodb_exporter#472]
Which open-source Grafana dashboards I can use if I'm using this mongodb-exporter? 
I'm trying to use: https://github.com/percona/grafana-dashboards/tree/main/dashboards/MongoDB
but the metrics they are using don't exist in the exporter.
Can you recommend on an open-source dashboard that suits the metrics in the mongodb-exporter?

**Comment by ShashankSinha252** [comment]
Hi @Shoham12 , please give [convert-dash-from-PMM.py](https://github.com/percona/grafana-dashboards/blob/main/misc/convert-dash-from-PMM.py) a shot. It's not perfect, but I'll be glad to iron out any issues.

**Comment by Shoham12** [comment]
Thanks @ShashankSinha252 !  I'm not able to run the script. I'm getting the below error: 
Dashboard: temp.json
Traceback (most recent call last):
  File "/Users/shohamlandau/automation_scripts/tests/test33.py", line 159, in <module>
    main()
  File "/Users/shohamlandau/automation_scripts/tests/test33.py", line 142, in main
    check_formulas(dashboard, "node_name", "instance")
  File "/Users/shohamlandau/automation_scripts/tests/test33.py", line 91, in check_formulas
    expr = re.sub('node_type=~\"[a-z,$_|]*\"', '', expr)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by ShashankSinha252** [comment]
Let me take a stab at it and get back to you on this, @Shoham12

**Comment by shardulsrivastava** [comment]
@Shoham12 Here is the fix for the python script :

https://github.com/percona/grafana-dashboards/pull/1301

I tested it, Just add these lines at line number 108 : 

```py
if isinstance(expr, dict) and ('query' in expr):
                            expr = expr['query']
```

**Comment by ShashankSinha252** [comment]
Hi @Shoham12 , above mentioned PR has been merged. Can you give it a shot now and confirm if things are working for you?

**Comment by Shoham12** [comment]
@ShashankSinha252 The code works properly now but still the metrics are not available on my Prometheus so I'm still getting blank charts in Grafana.
For example, I'm trying to use: 
https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Cluster_Summary.json
and still the metrics are not available on my Prometheus. As result, I don't see any stats in Grafana

**Comment by ShashankSinha252** [comment]
Can you check and confirm metrics generated by exporter end up in Prometheus? If there are no metrics available with Prometheus, as you mentioned, we will not see anything in Grafana.

In case of no metrics hitting Prometheus, please check status of exporter and connectivity from exporter to Prometheus.

**Comment by madhur** [comment]
I am having same issue, exporter is up and running. But I do not see anything in Grafana dashboard. Using this one
https://grafana.com/grafana/dashboards/7353

Here is the output of exporter

```
# HELP go_gc_cycles_automatic_gc_cycles_total Count of completed GC cycles generated by the Go runtime.
# TYPE go_gc_cycles_automatic_gc_cycles_total counter
go_gc_cycles_automatic_gc_cycles_total 38
# HELP go_gc_cycles_forced_gc_cycles_total Count of completed GC cycles forced by the application.
# TYPE go_gc_cycles_forced_gc_cycles_total counter
go_gc_cycles_forced_gc_cycles_total 0
# HELP go_gc_cycles_total_gc_cycles_total Count of all completed GC cycles.
# TYPE go_gc_cycles_total_gc_cycles_total counter
go_gc_cycles_total_gc_cycles_total 38
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.4368e-05
go_gc_duration_seconds{quantile="0.25"} 2.4707e-05
go_gc_duration_seconds{quantile="0.5"} 2.9046e-05
go_gc_duration_seconds{quantile="0.75"} 5.4825e-05
go_gc_duration_seconds{quantile="1"} 7.5052e-05
go_gc_duration_seconds_sum 0.00143013
go_gc_duration_seconds_count 38
# HELP go_gc_heap_allocs_by_size_bytes_total Distribution of heap allocations by approximate size. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
# TYPE go_gc_heap_allocs_by_size_bytes_total histogram
go_gc_heap_allocs_by_size_bytes_total_bucket{le="8.999999999999998"} 11418
go_gc_heap_allocs_by_size_bytes_total_bucket{le="24.999999999999996"} 88147
go_gc_heap_allocs_by_size_bytes_total_bucket{le="64.99999999999999"} 124945
go_gc_heap_allocs_by_size_bytes_total_bucket{le="144.99999999999997"} 151429
go_gc_heap_allocs_by_size_bytes_total_bucket{le="320.99999999999994"} 160524
go_gc_heap_allocs_by_size_bytes_total_bucket{le="704.9999999999999"} 164938
go_gc_heap_allocs_by_size_bytes_total_bucket{le="1536.9999999999998"} 166415
go_gc_heap_allocs_by_size_bytes_total_bucket{le="3200.9999999999995"} 166970
go_gc_heap_allocs_by_size_bytes_total_bucket{le="6528.999999999999"} 167506
go_gc_heap_allocs_by_size_bytes_total_bucket{le="13568.999999999998"} 167619
go_gc_heap_allocs_by_size_bytes_total_bucket{le="27264.999999999996"} 167926
go_gc_heap_allocs_by_size_bytes_total_bucket{le="+Inf"} 168127
go_gc_heap_allocs_by_size_bytes_total_sum 5.3973e+07
go_gc_heap_allocs_by_size_bytes_total_count 168127
# HELP go_gc_heap_allocs_bytes_total Cumulative sum of memory allocated to the heap by the application.
# TYPE go_gc_heap_allocs_bytes_total counter
go_gc_heap_allocs_bytes_total 5.3973e+07
# HELP go_gc_heap_allocs_objects_total Cumulative count of heap allocations triggered by the application. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
# TYPE go_gc_heap_allocs_objects_total counter
go_gc_heap_allocs_objects_total 168127
# HELP go_gc_heap_frees_by_size_bytes_total Distribution of freed heap allocations by approximate size. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
# TYPE go_gc_heap_frees_by_size_bytes_total histogram
go_gc_heap_frees_by_size_bytes_total_bucket{le="8.999999999999998"} 8326
go_gc_heap_frees_by_size_bytes_total_bucket{le="24.999999999999996"} 76655
go_gc_heap_frees_by_size_bytes_total_bucket{le="64.99999999999999"} 108965
go_gc_heap_frees_by_size_bytes_total_bucket{le="144.99999999999997"} 132557
go_gc_heap_frees_by_size_bytes_total_bucket{le="320.99999999999994"} 140163
go_gc_heap_frees_by_size_bytes_total_bucket{le="704.9999999999999"} 143947
go_gc_heap_frees_by_size_bytes_total_bucket{le="1536.9999999999998"} 145248
go_gc_heap_frees_by_size_bytes_total_bucket{le="3200.9999999999995"} 145729
go_gc_heap_frees_by_size_bytes_total_bucket{le="6528.999999999999"} 146211
go_gc_heap_frees_by_size_bytes_total_bucket{le="13568.999999999998"} 146300
go_gc_heap_frees_by_size_bytes_total_bucket{le="27264.999999999996"} 146596
go_gc_heap_frees_by_size_bytes_total_bucket{le="+Inf"} 146787
go_gc_heap_frees_by_size_bytes_total_sum 5.0457688e+07
go_gc_heap_frees_by_size_bytes_total_count 146787
# HELP go_gc_heap_frees_bytes_total Cumulative sum of heap memory freed by the garbage collector.
# TYPE go_gc_heap_frees_bytes_total counter
go_gc_heap_frees_bytes_total 5.0457688e+07
# HELP go_gc_heap_frees_objects_total Cumulative count of heap allocations whose storage was freed by the garbage collector. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.
# TYPE go_gc_heap_frees_objects_total counter
go_gc_heap_frees_objects_total 146787
# HELP go_gc_heap_goal_bytes Heap size target for the end of the GC cycle.
# TYPE go_gc_heap_goal_bytes gauge
go_gc_heap_goal_bytes 4.194304e+06
# HELP go_gc_heap_objects_objects Number of objects, live or unswept, occupying heap memory.
# TYPE go_gc_heap_objects_objects gauge
go_gc_heap_objects_objects 21340
# HELP go_gc_heap_tiny_allocs_objects_total Count of small allocations that are packed together into blocks. These allocations are counted separately from other allocations because each individual allocation is not tracked by the runtime, only their block. Each block is already accounted for in allocs-by-size and frees-by-size.
# TYPE go_gc_heap_tiny_allocs_objects_total counter
go_gc_heap_tiny_allocs_objects_total 18985
# HELP go_gc_pauses_seconds_total Distribution individual GC-related stop-the-world pause latencies.
# TYPE go_gc_pauses_seconds_total histogram
go_gc_pauses_seconds_total_bucket{le="-5e-324"} 0
go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-10"} 0
go_gc_pauses_seconds_total_bucket{le="9.999999999999999e-09"} 0
go_gc_pauses_seconds_total_bucket{le="9.999999999999998e-08"} 0
go_gc_pauses_seconds_total_bucket{le="1.0239999999999999e-06"} 0
go_gc_pauses_seconds_total_bucket{le="1.0239999999999999e-05"} 36
go_gc_pauses_seconds_total_bucket{le="0.00010239999999999998"} 76
go_gc_pauses_seconds_total_bucket{le="0.0010485759999999998"} 76
go_gc_pauses_seconds_total_bucket{le="0.010485759999999998"} 76
go_gc_pauses_seconds_total_bucket{le="0.10485759999999998"} 76
go_gc_pauses_seconds_total_bucket{le="+Inf"} 76
go_gc_pauses_seconds_total_sum NaN
go_gc_pauses_seconds_total_count 76
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 19
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.17.8"} 1
# HELP go_memory_classes_heap_free_bytes Memory that is completely free and eligible to be returned to the underlying system, but has not been. This metric is the runtime's estimate of free address space that is backed by physical memory.
# TYPE go_memory_classes_heap_free_bytes gauge
go_memory_classes_heap_free_bytes 245760
# HELP go_memory_classes_heap_objects_bytes Memory occupied by live objects and dead objects that have not yet been marked free by the garbage collector.
# TYPE go_memory_classes_heap_objects_bytes gauge
go_memory_classes_heap_objects_bytes 3.515312e+06
# HELP go_memory_classes_heap_released_bytes Memory that is completely free and has been returned to the underlying system. This metric is the runtime's estimate of free address space that is still mapped into the process, but is not backed by physical memory.
# TYPE go_memory_classes_heap_released_bytes gauge
go_memory_classes_heap_released_bytes 6.701056e+06
# HELP go_memory_classes_heap_stacks_bytes Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.
# TYPE go_memory_classes_heap_stacks_bytes gauge
go_memory_classes_heap_stacks_bytes 1.212416e+06
# HELP go_memory_classes_heap_unused_bytes Memory that is reserved for heap objects but is not currently used to hold heap objects.
# TYPE go_memory_classes_heap_unused_bytes gauge
go_memory_classes_heap_unused_bytes 908368
# HELP go_memory_classes_metadata_mcache_free_bytes Memory that is reserved for runtime mcache structures, but not in-use.
# TYPE go_memory_classes_metadata_mcache_free_bytes gauge
go_memory_classes_metadata_mcache_free_bytes 1984
# HELP go_memory_classes_metadata_mcache_inuse_bytes Memory that is occupied by runtime mcache structures that are currently being used.
# TYPE go_memory_classes_metadata_mcache_inuse_bytes gauge
go_memory_classes_metadata_mcache_inuse_bytes 14400
# HELP go_memory_classes_metadata_mspan_free_bytes Memory that is reserved for runtime mspan structures, but not in-use.
# TYPE go_memory_classes_metadata_mspan_free_bytes gauge
go_memory_classes_metadata_mspan_free_bytes 16816
# HELP go_memory_classes_metadata_mspan_inuse_bytes Memory that is occupied by runtime mspan structures that are currently being used.
# TYPE go_memory_classes_metadata_mspan_inuse_bytes gauge
go_memory_classes_metadata_mspan_inuse_bytes 179792
# HELP go_memory_classes_metadata_other_bytes Memory that is reserved for or used to hold runtime metadata.
# TYPE go_memory_classes_metadata_other_bytes gauge
go_memory_classes_metadata_other_bytes 4.888624e+06
# HELP go_memory_classes_os_stacks_bytes Stack memory allocated by the underlying operating system.
# TYPE go_memory_classes_os_stacks_bytes gauge
go_memory_classes_os_stacks_bytes 0
# HELP go_memory_classes_other_bytes Memory used by execution trace buffers, structures for debugging the runtime, finalizer and profiler specials, and more.
# TYPE go_memory_classes_other_bytes gauge
go_memory_classes_other_bytes 2.449448e+06
# HELP go_memory_classes_profiling_buckets_bytes Memory that is used by the stack trace hash map used for profiling.
# TYPE go_memory_classes_profiling_buckets_bytes gauge
go_memory_classes_profiling_buckets_bytes 4792
# HELP go_memory_classes_total_bytes All memory mapped by the Go runtime into the current process as read-write. Note that this does not include memory mapped by code called via cgo or via the syscall package. Sum of all metrics in /memory/classes.
# TYPE go_memory_classes_total_bytes gauge
go_memory_classes_total_bytes 2.0138768e+07
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 3.515312e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.3973e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 4792
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 165772
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 0
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 4.888624e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 3.515312e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.946816e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 4.42368e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 21340
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 6.701056e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.1370496e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6512519563797946e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 187112
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 14400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 179792
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 196608
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 2.449448e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.212416e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.212416e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.0138768e+07
# HELP go_sched_goroutines_goroutines Count of live goroutines.
# TYPE go_sched_goroutines_goroutines gauge
go_sched_goroutines_goroutines 18
# HELP go_sched_latencies_seconds Distribution of the time goroutines have spent in the scheduler in a runnable state before actually running.
# TYPE go_sched_latencies_seconds histogram
go_sched_latencies_seconds_bucket{le="-5e-324"} 0
go_sched_latencies_seconds_bucket{le="9.999999999999999e-10"} 1020
go_sched_latencies_seconds_bucket{le="9.999999999999999e-09"} 1020
go_sched_latencies_seconds_bucket{le="9.999999999999998e-08"} 1636
go_sched_latencies_seconds_bucket{le="1.0239999999999999e-06"} 2221
go_sched_latencies_seconds_bucket{le="1.0239999999999999e-05"} 3155
go_sched_latencies_seconds_bucket{le="0.00010239999999999998"} 3437
go_sched_latencies_seconds_bucket{le="0.0010485759999999998"} 3441
go_sched_latencies_seconds_bucket{le="0.010485759999999998"} 3441
go_sched_latencies_seconds_bucket{le="0.10485759999999998"} 3441
go_sched_latencies_seconds_bucket{le="+Inf"} 3441
go_sched_latencies_seconds_sum NaN
go_sched_latencies_seconds_count 3441
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 15
# HELP mongodb_up Whether MongoDB is up.
# TYPE mongodb_up gauge
mongodb_up 1
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 130.23
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 18
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.054144e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.65125113455e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.3684992e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
```

**Comment by ShashankSinha252** [comment]
@madhur , are you running v0.3x version of exporter? If yes, please check out #477

**Comment by mobinzk** [comment]
@ShashankSinha252 I've used your reference, added the following attributes, and it resolved the issue. Hope this helps @madhur as well.

`--collect-all --compatible-mode`

**Comment by ShashankSinha252** [comment]
Thanks for the confirmation @mobinzk ! @madhur , please check and let us know.
